version: "3.9"

services:
  ovn:
    build:
      context: .
      dockerfile: Dockerfile
    image: ovn-allinone:25.03.1
    container_name: ovn
    hostname: ${NODE_NAME}
    restart: always
    privileged: true
    network_mode: host
    pid: host

    environment:
      NODE_NAME: ${NODE_NAME}
      ROLE: ${ROLE}
      BOOTSTRAP_IP: ${BOOTSTRAP_IP}

      PHYS_BR: br-phys
      PHYSNET_NAME: physnet
      BOND_PORT: ${BOND_PORT}
      ALLOWED_VLANS: "10,20"

      MGMT_VLAN: "10"
      MGMT_IFACE: ovs-mgmt
      MGMT_CIDR: ${MGMT_CIDR}
      MGMT_IP: ${MGMT_IP}
      MGMT_GW: ${MGMT_GW}
      LINSTOR_VLAN: "20"
      LINSTOR_IFACE: linstor-mgmt
      LINSTOR_CIDR: ${LINSTOR_CIDR}
      MTU: "9000"

      ENCAP_TYPE: geneve
      ENCAP_IP: ${MGMT_IP}

      NB_REMOTES: "tcp:4.0.0.7:6641,tcp:4.0.0.8:6641,tcp:4.0.0.9:6641"
      SB_REMOTES: "tcp:4.0.0.7:6642,tcp:4.0.0.8:6642,tcp:4.0.0.9:6642"

    volumes:
      - /lib/modules:/lib/modules:ro
      - ./state/openvswitch:/var/lib/openvswitch
      - ./state/ovn:/var/lib/ovn
      - ./scripts/entrypoint.sh:/entrypoint.sh:ro
      - ./scripts/checks.sh:/scripts/checks.sh:ro

    entrypoint: ["/bin/bash", "/entrypoint.sh"]

    healthcheck:
      test: ["CMD-SHELL", "ovs-vsctl --timeout=2 show >/dev/null 2>&1 && ovn-appctl -t ovn-northd status >/dev/null 2>&1"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 25s
